---
format_version: '13'
default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
project_type: android
include:
  - path: config/bitrise-common.yml
  - path: bitrise.yml
    branch: main
    repository: bitrise-base
workflows:
  workflow-setup-dev:
    envs:
    - ENV_TYPE: DEV
    steps:
    - bundle::project_setup: {}
  workflow-setup-prod:
    envs:
    - ENV_TYPE: PROD
    steps:
    - bundle::project_setup: {}
  test-android:
    envs:
    - TEST_PLAN: ANDROID
    steps:
    - bundle::run_test: {}
  test-ios:
    envs:
    - TEST_PLAN: IOS
    steps:
    - bundle::run_test: {}
meta:
  bitrise.io:
    stack: linux-docker-android-22.04
    machine_type_id: elite-xl
pipelines:
  dev-pipeline:
    workflows:
      workflow-setup-dev: {}
      test-android:
        depends_on:
        - workflow-setup-dev
      test-ios:
        depends_on:
        - workflow-setup-dev
    triggers:
      pull_request:
      - target_branch: main
  prod-pipeline:
    workflows:
      workflow-setup-prod: {}
      test-android:
        depends_on:
        - workflow-setup-prod
      test-ios:
        depends_on:
        - workflow-setup-prod
    triggers:
      push:
      - branch: main